import moment from "moment";
import i18n from "../../../i18n/index.js";

/* eslint-disable no-useless-computed-key */

export const mockedData = [
  {
    id: 1,
    companyName: "Klaston",
    departmentName: "Departamento de Produção",
    category: "Produção",
    author: "João",
    documentName: "Documento 1",
    revision: "1",
    validity: "Validade 1",
    revisionDate: "Data de revisão 1",
  },
  {
    id: 2,
    companyName: "Klaston",
    departmentName: "Departamento de Vendas",
    category: "Vendas",
    author: "Maria",
    documentName: "Documento 2",
    revision: "1",
    validity: "Validade 2",
    revisionDate: "Data de revisão 2",
  },
  {
    id: 3,
    companyName: "Klaston",
    departmentName: "Departamento de Marketing",
    category: "Marketing",
    author: "Carlos",
    documentName: "Documento 3",
    revision: "2",
    validity: "Validade 3",
    revisionDate: "Data de revisão 3",
  },
  {
    id: 4,
    companyName: "Klaston",
    departmentName: "Departamento de TI",
    category: "Tecnologia",
    author: "Ana",
    documentName: "Documento 4",
    revision: "3",
    validity: "Validade 4",
    revisionDate: "Data de revisão 4",
  },
  {
    id: 5,
    companyName: "Klaston",
    departmentName: "Departamento de RH",
    category: "Recursos Humanos",
    author: "Pedro",
    documentName: "Documento 5",
    revision: "2",
    validity: "Validade 5",
    revisionDate: "Data de revisão 5",
  },
  {
    id: 6,
    companyName: "Klaston",
    departmentName: "Departamento Jurídico",
    category: "Legal",
    author: "Fernanda",
    documentName: "Documento 6",
    revision: "1",
    validity: "Validade 6",
    revisionDate: "Data de revisão 6",
  },
  {
    id: 7,
    companyName: "Klaston",
    departmentName: "Departamento Financeiro",
    category: "Financeiro",
    author: "Rafael",
    documentName: "Documento 7",
    revision: "3",
    validity: "Validade 7",
    revisionDate: "Data de revisão 7",
  },
  {
    id: 8,
    companyName: "Klaston",
    departmentName: "Departamento de Compras",
    category: "Compras",
    author: "Lucas",
    documentName: "Documento 8",
    revision: "2",
    validity: "Validade 8",
    revisionDate: "Data de revisão 8",
  },
  {
    id: 9,
    companyName: "Klaston",
    departmentName: "Departamento de Logística",
    category: "Logística",
    author: "Beatriz",
    documentName: "Documento 9",
    revision: "1",
    validity: "Validade 9",
    revisionDate: "Data de revisão 9",
  },
  {
    id: 10,
    companyName: "Klaston",
    departmentName: "Departamento de Pesquisa e Desenvolvimento",
    category: "P&D",
    author: "Rodrigo",
    documentName: "Documento 10",
    revision: "3",
    validity: "Validade 10",
    revisionDate: "Data de revisão 10",
  },
];
export const columns = [
  // Remove or comment out the code column definition
  // {
  //   Header: "Código",
  //   accessor: "code",
  // },
  {
    header: i18n.t("Empresa"),
    access: "companyName",
  },
  {
    header: i18n.t("Departamento"),
    access: "departamentName",
  },
  {
    header: i18n.t("Categoria"),
    access: "categoryName",
  },
  {
    header: i18n.t("Autor"),
    access: "owner",
  },
  {
    header: i18n.t("Nome"),
    access: "name",
  },
  {
    header: i18n.t("Revisão"),
    access: "revision",
  },
  {
    header: i18n.t("Validade"),
    access: "validity",
  },
  {
    header: i18n.t("Data de revisão"),
    access: "revisionDate",
    formatData: (data) => moment.utc(data).format("DD/MM/YYYY"),
  },
].filter(Boolean);
