const DOCUMENTS_EVENTS = {
  DOCUMENTS_GET: "DOCUMENTS_GET",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
  DOCUMENT_CREATED: "DOCUMENT_CREATED",
  DOCUMENT_UPDATED: "DOCUMENT_UPDATED",
  //Detalhes do documento
  DOCUMENTS_DETAILS_GET: "DOCUMENTS_DETAILS_GET",
  DOCUMENT_DETAILS_FEED_CREATED: "DOCUMENT_DETAILS_FEED_CREATED",
  DOCUMENT_DETAILS_FEED_DELETED: "DOCUMENT_DETAILS_FEED_DELETED",
  DOCUMENT_DETAILS_FEED_UPDATED: "DOCUMENT_DETAILS_FEED_UPDATED",
  DOCUMENTS_DETAILS_ADD_ADDITIONAL_DOCUMENT:
    "DOCUMENTS_DETAILS_ADD_ADDITIONAL_DOCUMENT",
  DOCUMENTS_DETAILS_DELETE_ADDITIONAL_DOCUMENT:
    "DOCUMENTS_DETAILS_DELETE_ADDITIONAL_DOCUMENT",

  //Revisoes
  DOCUMENTS_DETAILS_ADD_REVISION: "DOCUMENTS_DETAILS_ADD_REVISION",
  DOCUMENTS_DETAILS_EDIT_REVISION: "DOCUMENTS_DETAILS_EDIT_REVISION",
  DOCUMENTS_DETAILS_DELETE_REVISION: "DOCUMENTS_DETAILS_DELETE_REVISION",

  //Avaliaçoes
  DOCUMENTS_DETAILS_ADD_EVALUATOR: "DOCUMENTS_DETAILS_ADD_EVALUATOR",
  DOCUMENTS_DETAILS_DELETE_EVALUATOR: "DOCUMENTS_DETAILS_DELETE_EVALUATOR",

  // Relacionados
  DOCUMENTS_DETAILS_ADD_RELATED: "DOCUMENTS_DETAILS_ADD_RELATED",
  DOCUMENTS_DETAILS_DELETE_RELATED: "DOCUMENTS_DETAILS_DELETE_RELATED",

  // Permissoes
  DOCUMENTS_DETAILS_ADD_DEPARTAMENT_PERMISSION:
    "DOCUMENTS_DETAILS_ADD_DEPARTAMENT_PERMISSION",
  DOCUMENTS_DETAILS_DELETE_DEPARTAMENT_PERMISSION:
    "DOCUMENTS_DETAILS_DELETE_DEPARTAMENT_PERMISSION",
};

export const AUDIT_EVENTS = {
  ...DOCUMENTS_EVENTS,
};
