import { Text } from "@chakra-ui/react";
import moment from "moment";
import HtmlParser from "react-html-parser";

export const columns = [
  {
    header: "Usuário",
    access: "username",
  },
  {
    header: "Cliente / Fornecedor",
    access: "crmCompanyName",
  },
  {
    header: "Status",
    access: "status",
  },
  {
    header: "Valor",
    access: "value",
  },
  {
    header: "Email",
    access: "email",
  },
  {
    header: "Telefone",
    access: "celphone",
  },
  {
    header: "Descrição",
    access: "description",
    formatData: (data) => {
      return <Text>{HtmlParser(data)}</Text>;
    },
  },
  {
    header: "Última atualização",
    access: "updatedAt",
    formatData: (data) =>
      data ? moment(data).format("DD/MM/YYYY HH:mm") : "Não houve atualizações",
  },
];

export const mockedData = [
  {
    id: 1,
    user: "Luiz Henrique da Cruz",
    clientName: "da Luz Costa - EI",
    status: "Pendente",
    value: "R$ 838000,00",
    email: "ucostela@bol.com.br",
    phone: "+55 (071) 0406 9810",
    description: "Dolorem reiciendis iste voluptatibus officiis aut.",
    updatedAt: "2007-12-30",
    reference: "Paola Medeiros",
    dealIsClosed: "Não",
    solicitationMonth: "Janeiro",
    solicitationYear: 2053,
  },
  {
    id: 2,
    user: "Maria Luiza Campos",
    clientName: "Barbosa S.A.",
    status: "Ativo",
    value: "R$ 647000,00",
    email: "hribeiro@silveira.com",
    phone: "+55 84 6899-8730",
    description:
      "Amet possimus blanditiis est tempora possimus possimus fugit.",
    updatedAt: "2020-07-14",
    reference: "BRuno",
  },
  {
    id: 3,
    user: "Clarice Porto",
    clientName: "Costa Gonçalves S/A",
    status: "Ativo",
    value: "R$ 562000,00",
    email: "da-matamilena@goncalves.com",
    phone: "+55 (081) 3632 5203",
    description: "Enim magni laboriosam tenetur quam sunt.",
    updatedAt: "2019-05-01",
  },
  {
    id: 4,
    user: "Dra. Emilly Souza",
    clientName: "Nogueira - EI",
    status: "Ativo",
    value: "R$ 897000,00",
    email: "gnascimento@ig.com.br",
    phone: "11 6661-3722",
    description: "Sint id soluta quam.",
    updatedAt: "2009-07-01",
  },
  {
    id: 5,
    user: "Srta. Luana Aragão",
    clientName: "Vieira Moraes S/A",
    status: "Pendente",
    value: "R$ 74000,00",
    email: "luigicosta@da.net",
    phone: "61 4809-3798",
    description: "Officia impedit officiis natus harum quidem.",
    updatedAt: "1997-06-07",
  },
  {
    id: 6,
    user: "Igor Peixoto",
    clientName: "Moreira Cavalcanti S/A",
    status: "Pendente",
    value: "R$ 528000,00",
    email: "vda-cruz@ig.com.br",
    phone: "81 5825-4175",
    description: "Impedit ab placeat officia impedit fugit enim.",
    updatedAt: "1999-01-15",
  },
  {
    id: 7,
    user: "Dr. Juan Viana",
    clientName: "Peixoto Ltda.",
    status: "Ativo",
    value: "R$ 911000,00",
    email: "pintoenrico@gmail.com",
    phone: "+55 21 0188 7224",
    description: "Rerum magnam non incidunt voluptatum.",
    updatedAt: "2004-12-27",
  },
  {
    id: 8,
    user: "Gustavo Henrique da Cruz",
    clientName: "Cardoso Araújo S/A",
    status: "Ativo",
    value: "R$ 132000,00",
    email: "teixeirarodrigo@das.net",
    phone: "+55 84 6040 2023",
    description: "Totam quam sunt culpa voluptates magnam nemo.",
    updatedAt: "1972-10-15",
  },
  {
    id: 9,
    user: "Pedro Lucas Fernandes",
    clientName: "Dias Araújo - EI",
    status: "Ativo",
    value: "R$ 860000,00",
    email: "jmelo@silveira.com",
    phone: "0800-449-4282",
    description: "Ipsum ad necessitatibus voluptate rerum quisquam.",
    updatedAt: "2020-03-08",
  },
  {
    id: 10,
    user: "Dr. Fernando Correia",
    clientName: "da Rocha",
    status: "Ativo",
    value: "R$ 709000,00",
    email: "gomespedro-miguel@da.org",
    phone: "+55 (041) 9839-2114",
    description: "Quasi maxime aspernatur aut ullam.",
    updatedAt: "1988-02-08",
  },
];

export const tasksColumns = [
  {
    header: "Cliente / Fornecedor",
    access: "clientName",
  },
  {
    header: "Data",
    access: "date",
    formatData: (data) => moment(data).format("DD/MM/YYYY"),
  },
  {
    header: "Tipo",
    access: "type",
  },
  {
    header: "Usuário",
    access: "userName",
  },
  {
    header: "Descrição",
    access: "description",
  },
];

export const tasksMockedData = [
  {
    id: 1,
    clientName: "da Luz Costa - EI",
    date: "2022-01-01",
    type: "Interno",
    user: "Luiz Henrique da Cruz",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 2,
    clientName: "Barbosa S.A.",
    date: "2022-01-01",
    type: "Externo",
    user: "Maria Luiza Campos",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 3,
    clientName: "Costa Gonçalves S/A",
    date: "2022-01-01",
    type: "Interno",
    user: "Clarice Porto",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 4,
    clientName: "Nogueira - EI",
    date: "2022-01-01",
    type: "Externo",
    user: "Dra. Emilly Souza",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 5,
    clientName: "Vieira Moraes S/A",
    date: "2022-01-01",
    type: "Interno",
    user: "Srta. Luana Aragão",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 6,
    clientName: "Peixoto Ltda.",
    date: "2022-01-01",
    type: "Externo",
    user: "Igor Peixoto",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 7,
    clientName: "Cardoso Araújo S/A",
    date: "2022-01-01",
    type: "Interno",
    user: "Dr. Juan Viana",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 8,
    clientName: "da Rocha",
    date: "2022-01-01",
    type: "Externo",
    user: "Pedro Lucas Fernandes",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 9,
    clientName: "Dias Araújo - EI",
    date: "2022-01-01",
    type: "Interno",
    user: "Dr. Fernando Correia",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id: 10,
    clientName: "da Rocha",
    date: "2022-01-01",
    type: "Externo",
    user: "Pedro Lucas Fernandes",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
];
