//Code, company, author, title, origen, classification, type, open, status
export const columns = [
  { header: "Código", access: "id" },
  { header: "Empresa", access: "companyName" },
  { header: "Autor", access: "owner" },
  { header: "Título", access: "name" },
  { header: "Origem", access: "origin" },
  { header: "Classificação", access: "classification" },
  { header: "Tipo", access: "type" },
  { header: "Aberto", access: "open" },
  { header: "Status", access: "status" },
];

export const mockedData = [
  {
    id: 1,
    companyName: "Klaston",
    owner: "João",
    name: "Task 1",
    origin: "Origem 1",
    classification: "Classificação 1",
    type: "Tipo 1",
    open: "28/10/2022",
    status: "Status 1",
  },
  {
    id: 2,
    companyName: "Klaston",
    owner: "Maria",
    name: "Task 2",
    origin: "Origem 2",
    classification: "Classificação 2",
    type: "Tipo 2",
    open: "28/10/2022",
    status: "Status 2",
  },
  {
    id: 3,
    companyName: "Klaston",
    owner: "Carlos",
    name: "Task 3",
    origin: "Origem 3",
    classification: "Classificação 3",
    type: "Tipo 3",
    open: "28/10/2022",
    status: "Status 3",
  },
  {
    id: 4,
    companyName: "Klaston",
    owner: "Ana",
    name: "Task 4",
    origin: "Origem 4",
    classification: "Classificação 4",
    type: "Tipo 4",
    open: "28/10/2022",
    status: "Status 4",
  },
  {
    id: 5,
    companyName: "Klaston",
    owner: "Pedro",
    name: "Task 5",
    origin: "Origem 5",
    classification: "Classificação 5",
    type: "Tipo 5",
    open: "28/10/2022",
    status: "Status 5",
  },
  {
    id: 6,
    companyName: "Klaston",
    owner: "Fernanda",
    name: "Task 6",
    origin: "Origem 6",
    classification: "Classificação 6",
    type: "Tipo 6",
    open: "28/10/2022",
    status: "Status 6",
  },
  {
    id: 7,
    companyName: "Klaston",
    owner: "Rafael",
    name: "Task 7",
    origin: "Origem 7",
    classification: "Classificação 7",
    type: "Tipo 7",
    open: "28/10/2022",
    status: "Status 7",
  },
  {
    id: 8,
    companyName: "Klaston",
    owner: "Lucas",
    name: "Task 8",
    origin: "Origem 8",
    classification: "Classificação 8",
    type: "Tipo 8",
    open: "28/10/2022",
    status: "Status 8",
  },
  {
    id: 10,
    companyName: "Klaston",
    owner: "Rodrigo",
    name: "Task 10",
    origin: "Origem 10",
    classification: "Classificação 10",
    type: "Tipo 10",
    open: "28/10/2022",
    status: "Status 10",
  },
];
