export const usersMock = [
  {
    company: "Klaston Managment",
    name: "Gabriela Silva1",
    email: "gabriela.silva@company.com",
    passwordHash: "$2b$10$randomHashValue", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "manager",
    departament: "Sales",
    birthday: "1985-11-21",
    status: "active",
    id: "unique-id-1",
  },
  {
    company: "Klaston Managment",
    name: "Pedro Santos2",
    email: "pedro.santos@company.com",
    passwordHash: "$2b$10$anotherRandomHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: true,
    projectAccess: false,
    accessRule: "developer",
    departament: "Engineering",
    birthday: "1995-03-07",
    status: "active",
    id: "unique-id-2",
  },
  {
    company: "Klaston Managment",
    name: "Sofia Oliveira3",
    email: "sofia.oliveira@company.com",
    passwordHash: "$2b$10$yetAnotherHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "marketing",
    departament: "Marketing",
    birthday: "1978-08-12",
    status: "active",
    id: "unique-id-3",
  },
  {
    company: "Klaston Managment",
    name: "Miguel Costa4",
    email: "miguel.costa@company.com",
    passwordHash: "$2b$10$superSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: true,
    accessRule: "designer",
    departament: "Design",
    birthday: "1992-02-25",
    status: "active",
    id: "unique-id-4",
  },
  {
    company: "Klaston Managment",
    name: "Ana Ribeiro5",
    email: "ana.ribeiro@company.com",
    passwordHash: "$2b$10$veryStrongHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "admin",
    departament: "Management",
    birthday: "1980-06-18",
    status: "active",
    id: "unique-id-5",
  },
  {
    company: "Klaston Managment",
    name: "Diogo Pereira6",
    email: "diogo.pereira@company.com",
    passwordHash: "$2b$10$anotherSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: false,
    accessRule: "user",
    departament: "Finance",
    birthday: "1968-10-04",
    status: "active",
    id: "unique-id-6",
  },
  {
    company: "Klaston Managment",
    name: "Catarina Sousa7",
    email: "catarina.sousa@company.com",
    passwordHash: "$2b$10$verySecureHashHere",
    status: "STATUS",
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "qa",
    id: "unique-id-7",
  },
  // Novos usuários adicionados abaixo:
  {
    company: "Klaston Managment",
    name: "Lucas Alves8",
    email: "lucas.alves@company.com",
    passwordHash: "$2b$10$randomHashValue", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "manager",
    departament: "Sales",
    birthday: "1983-09-15",
    status: "active",
    id: "unique-id-8",
  },
  {
    company: "Klaston Managment",
    name: "Camila Lima9",
    email: "camila.lima@company.com",
    passwordHash: "$2b$10$anotherRandomHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: true,
    projectAccess: false,
    accessRule: "developer",
    departament: "Engineering",
    birthday: "1991-05-22",
    status: "active",
    id: "unique-id-9",
  },
  {
    company: "Klaston Managment",
    name: "Rafaela Fernandes10",
    email: "rafaela.fernandes@company.com",
    passwordHash: "$2b$10$yetAnotherHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "marketing",
    departament: "Marketing",
    birthday: "1976-11-08",
    status: "active",
    id: "unique-id-10",
  },
  {
    company: "Klaston Managment",
    name: "João Oliveira11",
    email: "joao.oliveira@company.com",
    passwordHash: "$2b$10$superSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: true,
    accessRule: "designer",
    departament: "Design",
    birthday: "1988-03-12",
    status: "active",
    id: "unique-id-11",
  },
  {
    company: "Klaston Managment",
    name: "Juliana Santos12",
    email: "juliana.santos@company.com",
    passwordHash: "$2b$10$veryStrongHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "admin",
    departament: "Management",
    birthday: "1985-07-29",
    status: "active",
    id: "unique-id-12",
  },
  {
    company: "Klaston Managment",
    name: "Diogo Pereira6",
    email: "diogo.pereira@company.com",
    passwordHash: "$2b$10$anotherSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: false,
    accessRule: "user",
    departament: "Finance",
    birthday: "1968-10-04",
    status: "active",
    id: "unique-id-6",
  },
  {
    company: "Klaston Managment",
    name: "Catarina Sousa7",
    email: "catarina.sousa@company.com",
    passwordHash: "$2b$10$verySecureHashHere",
    status: "STATUS",
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "qa",
    id: "unique-id-7",
  },
  // Novos usuários adicionados abaixo:
  {
    company: "Klaston Managment",
    name: "Lucas Alves8",
    email: "lucas.alves@company.com",
    passwordHash: "$2b$10$randomHashValue", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "manager",
    departament: "Sales",
    birthday: "1983-09-15",
    status: "active",
    id: "unique-id-8",
  },
  {
    company: "Klaston Managment",
    name: "Camila Lima9",
    email: "camila.lima@company.com",
    passwordHash: "$2b$10$anotherRandomHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: true,
    projectAccess: false,
    accessRule: "developer",
    departament: "Engineering",
    birthday: "1991-05-22",
    status: "active",
    id: "unique-id-9",
  },
  {
    company: "Klaston Managment",
    name: "Rafaela Fernandes10",
    email: "rafaela.fernandes@company.com",
    passwordHash: "$2b$10$yetAnotherHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "marketing",
    departament: "Marketing",
    birthday: "1976-11-08",
    status: "active",
    id: "unique-id-10",
  },
  {
    company: "Klaston Managment",
    name: "João Oliveira11",
    email: "joao.oliveira@company.com",
    passwordHash: "$2b$10$superSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: true,
    accessRule: "designer",
    departament: "Design",
    birthday: "1988-03-12",
    status: "active",
    id: "unique-id-11",
  },
  {
    company: "Klaston Managment",
    name: "Juliana Santos12",
    email: "juliana.santos@company.com",
    passwordHash: "$2b$10$veryStrongHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "admin",
    departament: "Management",
    birthday: "1985-07-29",
    status: "active",
    id: "unique-id-12",
  },
  {
    company: "Klaston Managment",
    name: "Diogo Pereira6",
    email: "diogo.pereira@company.com",
    passwordHash: "$2b$10$anotherSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: false,
    accessRule: "user",
    departament: "Finance",
    birthday: "1968-10-04",
    status: "active",
    id: "unique-id-6",
  },
  {
    company: "Klaston Managment",
    name: "Catarina Sousa7",
    email: "catarina.sousa@company.com",
    passwordHash: "$2b$10$verySecureHashHere",
    status: "STATUS",
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "qa",
    id: "unique-id-7",
  },
  // Novos usuários adicionados abaixo:
  {
    company: "Klaston Managment",
    name: "Lucas Alves8",
    email: "lucas.alves@company.com",
    passwordHash: "$2b$10$randomHashValue", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "manager",
    departament: "Sales",
    birthday: "1983-09-15",
    status: "active",
    id: "unique-id-8",
  },
  {
    company: "Klaston Managment",
    name: "Camila Lima9",
    email: "camila.lima@company.com",
    passwordHash: "$2b$10$anotherRandomHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: true,
    projectAccess: false,
    accessRule: "developer",
    departament: "Engineering",
    birthday: "1991-05-22",
    status: "active",
    id: "unique-id-9",
  },
  {
    company: "Klaston Managment",
    name: "Rafaela Fernandes10",
    email: "rafaela.fernandes@company.com",
    passwordHash: "$2b$10$yetAnotherHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "marketing",
    departament: "Marketing",
    birthday: "1976-11-08",
    status: "active",
    id: "unique-id-10",
  },
  {
    company: "Klaston Managment",
    name: "João Oliveira11",
    email: "joao.oliveira@company.com",
    passwordHash: "$2b$10$superSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: true,
    accessRule: "designer",
    departament: "Design",
    birthday: "1988-03-12",
    status: "active",
    id: "unique-id-11",
  },
  {
    company: "Klaston Managment",
    name: "Juliana Santos12",
    email: "juliana.santos@company.com",
    passwordHash: "$2b$10$veryStrongHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "admin",
    departament: "Management",
    birthday: "1985-07-29",
    status: "active",
    id: "unique-id-12",
  },
  {
    company: "Klaston Managment",
    name: "Diogo Pereira6",
    email: "diogo.pereira@company.com",
    passwordHash: "$2b$10$anotherSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: false,
    accessRule: "user",
    departament: "Finance",
    birthday: "1968-10-04",
    status: "active",
    id: "unique-id-6",
  },
  {
    company: "Klaston Managment",
    name: "Catarina Sousa7",
    email: "catarina.sousa@company.com",
    passwordHash: "$2b$10$verySecureHashHere",
    status: "STATUS",
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "qa",
    id: "unique-id-7",
  },
  // Novos usuários adicionados abaixo:
  {
    company: "Klaston Managment",
    name: "Lucas Alves8",
    email: "lucas.alves@company.com",
    passwordHash: "$2b$10$randomHashValue", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "manager",
    departament: "Sales",
    birthday: "1983-09-15",
    status: "active",
    id: "unique-id-8",
  },
  {
    company: "Klaston Managment",
    name: "Camila Lima9",
    email: "camila.lima@company.com",
    passwordHash: "$2b$10$anotherRandomHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: true,
    projectAccess: false,
    accessRule: "developer",
    departament: "Engineering",
    birthday: "1991-05-22",
    status: "active",
    id: "unique-id-9",
  },
  {
    company: "Klaston Managment",
    name: "Rafaela Fernandes10",
    email: "rafaela.fernandes@company.com",
    passwordHash: "$2b$10$yetAnotherHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: false,
    projectAccess: true,
    accessRule: "marketing",
    departament: "Marketing",
    birthday: "1976-11-08",
    status: "active",
    id: "unique-id-10",
  },
  {
    company: "Klaston Managment",
    name: "João Oliveira11",
    email: "joao.oliveira@company.com",
    passwordHash: "$2b$10$superSecureHash", // Replace with a secure password hash
    access: true,
    contractAccess: false,
    leadAccess: false,
    projectAccess: true,
    accessRule: "designer",
    departament: "Design",
    birthday: "1988-03-12",
    status: "active",
    id: "unique-id-11",
  },
  {
    company: "Klaston Managment",
    name: "Juliana Santos12",
    email: "juliana.santos@company.com",
    passwordHash: "$2b$10$veryStrongHash", // Replace with a secure password hash
    access: true,
    contractAccess: true,
    leadAccess: true,
    projectAccess: true,
    accessRule: "admin",
    departament: "Management",
    birthday: "1985-07-29",
    status: "active",
    id: "unique-id-12",
  },
];

export const columns = [
  { header: "Empresa", access: "company" },
  { header: "Nome", access: "name" },
  { header: "Email", access: "email" },
  { header: "Status", access: "status" },
  { header: "Regra", access: "accessRule" },
];
