import moment from "moment";

export const columns = [
  {
    header: "Titulo",
    access: "title",
  },
  {
    header: "Cliente / Fornecedor",
    access: "clientType",
  },
  {
    header: "Data de Início",
    access: "startDate",
    formatData: (data) => moment(data).format("DD/MM/YYYY"),
  },
  {
    header: "Data de Término",
    access: "endDate",
    formatData: (data) => moment(data).format("DD/MM/YYYY"),
  },
  {
    header: "Valor",
    access: "value",
  },
  {
    header: "Detalhes",
    access: "details",
  },
  {
    header: "Status",
    access: "status",
  },
];

export const mockedData = [
  {
    id: 1,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Cliente",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Inativo",
  },
  {
    id: 2,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Fornecedor",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Ativo",
  },
  {
    id: 3,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Cliente",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Inativo",
  },
  {
    id: 4,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Fornecedor",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Ativo",
  },
  {
    id: 5,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Cliente",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Inativo",
  },
  {
    id: 6,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Fornecedor",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Ativo",
  },
  {
    id: 7,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Cliente",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Inativo",
  },
  {
    id: 8,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Fornecedor",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Ativo",
  },
  {
    id: 9,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Cliente",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Inativo",
  },
  {
    id: 10,
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    clientType: "Fornecedor",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    value: "R$ 100.000,00",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    status: "Ativo",
  },
];
